name: Docker Image CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [logger, viewer]

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ${{ matrix.directory }}
        run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}-${{ matrix.directory }}:$(date +%s)
